# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danielk/repos/KafkaCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danielk/repos/KafkaCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danielk/repos/KafkaCpp/CMakeFiles /home/danielk/repos/KafkaCpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danielk/repos/KafkaCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kafkacpp

# Build rule for target.
kafkacpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kafkacpp
.PHONY : kafkacpp

# fast build rule for target.
kafkacpp/fast:
	$(MAKE) -f CMakeFiles/kafkacpp.dir/build.make CMakeFiles/kafkacpp.dir/build
.PHONY : kafkacpp/fast

#=============================================================================
# Target rules for targets named Kafka

# Build rule for target.
Kafka: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Kafka
.PHONY : Kafka

# fast build rule for target.
Kafka/fast:
	$(MAKE) -f CMakeFiles/Kafka.dir/build.make CMakeFiles/Kafka.dir/build
.PHONY : Kafka/fast

main/consumer_main.o: main/consumer_main.cpp.o

.PHONY : main/consumer_main.o

# target to build an object file
main/consumer_main.cpp.o:
	$(MAKE) -f CMakeFiles/Kafka.dir/build.make CMakeFiles/Kafka.dir/main/consumer_main.cpp.o
.PHONY : main/consumer_main.cpp.o

main/consumer_main.i: main/consumer_main.cpp.i

.PHONY : main/consumer_main.i

# target to preprocess a source file
main/consumer_main.cpp.i:
	$(MAKE) -f CMakeFiles/Kafka.dir/build.make CMakeFiles/Kafka.dir/main/consumer_main.cpp.i
.PHONY : main/consumer_main.cpp.i

main/consumer_main.s: main/consumer_main.cpp.s

.PHONY : main/consumer_main.s

# target to generate assembly for a file
main/consumer_main.cpp.s:
	$(MAKE) -f CMakeFiles/Kafka.dir/build.make CMakeFiles/Kafka.dir/main/consumer_main.cpp.s
.PHONY : main/consumer_main.cpp.s

src/Events.o: src/Events.cpp.o

.PHONY : src/Events.o

# target to build an object file
src/Events.cpp.o:
	$(MAKE) -f CMakeFiles/kafkacpp.dir/build.make CMakeFiles/kafkacpp.dir/src/Events.cpp.o
.PHONY : src/Events.cpp.o

src/Events.i: src/Events.cpp.i

.PHONY : src/Events.i

# target to preprocess a source file
src/Events.cpp.i:
	$(MAKE) -f CMakeFiles/kafkacpp.dir/build.make CMakeFiles/kafkacpp.dir/src/Events.cpp.i
.PHONY : src/Events.cpp.i

src/Events.s: src/Events.cpp.s

.PHONY : src/Events.s

# target to generate assembly for a file
src/Events.cpp.s:
	$(MAKE) -f CMakeFiles/kafkacpp.dir/build.make CMakeFiles/kafkacpp.dir/src/Events.cpp.s
.PHONY : src/Events.cpp.s

src/KafkaConsumer.o: src/KafkaConsumer.cpp.o

.PHONY : src/KafkaConsumer.o

# target to build an object file
src/KafkaConsumer.cpp.o:
	$(MAKE) -f CMakeFiles/kafkacpp.dir/build.make CMakeFiles/kafkacpp.dir/src/KafkaConsumer.cpp.o
.PHONY : src/KafkaConsumer.cpp.o

src/KafkaConsumer.i: src/KafkaConsumer.cpp.i

.PHONY : src/KafkaConsumer.i

# target to preprocess a source file
src/KafkaConsumer.cpp.i:
	$(MAKE) -f CMakeFiles/kafkacpp.dir/build.make CMakeFiles/kafkacpp.dir/src/KafkaConsumer.cpp.i
.PHONY : src/KafkaConsumer.cpp.i

src/KafkaConsumer.s: src/KafkaConsumer.cpp.s

.PHONY : src/KafkaConsumer.s

# target to generate assembly for a file
src/KafkaConsumer.cpp.s:
	$(MAKE) -f CMakeFiles/kafkacpp.dir/build.make CMakeFiles/kafkacpp.dir/src/KafkaConsumer.cpp.s
.PHONY : src/KafkaConsumer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kafkacpp"
	@echo "... Kafka"
	@echo "... main/consumer_main.o"
	@echo "... main/consumer_main.i"
	@echo "... main/consumer_main.s"
	@echo "... src/Events.o"
	@echo "... src/Events.i"
	@echo "... src/Events.s"
	@echo "... src/KafkaConsumer.o"
	@echo "... src/KafkaConsumer.i"
	@echo "... src/KafkaConsumer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

